### ISSUE TITLE
Who is responsible for Fog, Wind, and Humidity?

### ISSUE THREAD

**Issue by MartinRoth** [MartinRoth/knmitransformer#10]

**Comment by cphotiadou** [comment]
good question!

**Comment by MartinRoth** [comment]
Rudmer said that these are handled directly by the modeling department...

**Comment by cphotiadou** [comment]
Fog: Reinout Boers 
Wind: Andreas Sterl (EC-EARTH)
Humidity : Geert Lenderik (RACMO)
