### ISSUE TITLE
Temperature

### ISSUE THREAD

**Issue by cphotiadou** [MartinRoth/knmitransformer#16]
Winter
year to year variation
coldest winter day per year (minimum tmean)
warmest winter day per year (maximum tmean)
frost days
ice days

Summer
year to year variation
coldest summer day per year (minimum tmean)
warmest summer day per year (maximum tmean)
summer days
tropical nights

**Comment by MartinRoth** [comment]
Transformation of temperature data is finished - now indices need to be calculated

**Comment by MartinRoth** [comment]
see cphotiadou/scenarioIndices#4
