### ISSUE TITLE
Precipitation

### ISSUE THREAD

**Issue by cphotiadou** [MartinRoth/knmitransformer#17]
Winter
year to year variation
10daily precipitation amount that is exceeded once in 10 years (Rudmer TF with GEV fit)
 number of wet days (>0.1mm)
number of heavy precip days (> 20mm)

Summer
year to year variation
daily precipitation amount that is exceeded once in 10 years (Rudmer TF with GEV fit)
 number of wet days (>0.1mm)
number of heavy precip days (> 20mm)

**Comment by MartinRoth** [comment]
see cphotiadou/scenarioIndices#3
