### ISSUE TITLE
refdata should be the same with the test data

### ISSUE THREAD

**Issue by cphotiadou** [MartinRoth/knmitransformer#62]
currently the test data include tg, tx, tn, evmk, rsds and rrcentr
The refdata in inst folder only include tg, evmk and rsds
the two should include the same ref data

**Comment by MartinRoth** [comment]
Actually the regressionInput folder should move (almost) completely to refdata in this case. There should be no need to keep two copies in the same repository ... Then on the other hand, there is the https://github.com/bessembi/knmitransformerReeksen data package ...
